### ISSUE TITLE
Add option to increase/decrease level of redundancy

### ISSUE THREAD

**Issue by francois-rozet** [Midbin/cades#1]
Hello, thank you for your package!

QR codes have several levels of redundancy which increases/decreases their size. It would be great if `cades` allowed to choose the redundancy in order to increase the robustness or reduce the number of pixels.

**Comment by Midbin** [comment]
Thanks for your suggestion. 

With version 0.3.0 I added support for qr code error correction levels.
They should be available using the typst package manager as soon as [this](https://github.com/typst/packages/pull/253) PR lands.

**Comment by francois-rozet** [comment]
Thank you!
